In [1]:
from selenium import webdriver
from webdriver_manager.firefox import GeckoDriverManager
import time
import csv
import pandas as pd

# 1) Wikipedia: Youtube video with most views

In [4]:
def wiki():
    csv_file = open('youtube_rankings.csv', 'w')
    writer = csv.writer(csv_file)
    writer.writerow(['Rank', 'Name', 'Uploader/Artist', 'Views', 'Date'])
    driver = webdriver.Firefox(executable_path = GeckoDriverManager().install())
    driver.get('https://en.wikipedia.org/wiki/List_of_most-viewed_YouTube_videos')
    time.sleep(5)
    for i in range(1,31):
        rank = i
        try:
            name = driver.find_element_by_css_selector('table.wikitable:nth-child(20) > tbody:nth-child(3) > tr:nth-child({}) > td:nth-child(2) > a:nth-child(1)'.format(i)).text
        except:
            body = driver.find_elements_by_css_selector('table.wikitable:nth-child(20) > tbody:nth-child(3) > tr:nth-child({}) > td:nth-child(2) > i:nth-child(1) > a:nth-child(1)'.format(i))
            if len(body) > 0:
                name = body[0].text
            else:
                name = driver.find_element_by_css_selector('table.wikitable:nth-child(20) > tbody:nth-child(3) > tr:nth-child({}) > td:nth-child(2)'.format(i)).text
        artist = driver.find_element_by_css_selector('table.wikitable:nth-child(20) > tbody:nth-child(3) > tr:nth-child({}) > td:nth-child(3)'.format(i)).text
        views = driver.find_element_by_css_selector('table.wikitable:nth-child(20) > tbody:nth-child(3) > tr:nth-child({}) > td:nth-child(4)'.format(i)).text
        date = driver.find_element_by_css_selector('table.wikitable:nth-child(20) > tbody:nth-child(3) > tr:nth-child({}) > td:nth-child(5)'.format(i)).text
        writer.writerow([i, name, artist, views, date])
    csv_file.close()

In [5]:
wiki()
pd.read_csv('youtube_rankings.csv')

[WDM] - Driver [/home/aditya/.wdm/drivers/geckodriver/linux64/v0.29.0/geckodriver] found in cache

,Rank,Name,Uploader/Artist,Views,Date
0,1,Baby Shark Dance,Pinkfong Kids' Songs & Stories,7.85,"June 17, 2016"
1,2,Despacito,Luis Fonsi featuring Daddy Yankee,7.19,"January 12, 2017"
2,3,Shape of You,Ed Sheeran,5.18,"January 30, 2017"
3,4,See You Again,Wiz Khalifa featuring Charlie Puth,4.94,"April 6, 2015"
4,5,Johny Johny Yes Papa,LooLoo Kids,4.73,"October 8, 2016"
5,6,Masha and the Bear,Get Movies,4.41,"January 31, 2012"
6,7,Uptown Funk,Mark Ronson featuring Bruno Mars,4.08,"November 19, 2014"
7,8,Gangnam Style,Psy,3.96,"July 15, 2012"
8,9,"""Learning Colors – Colorful Eggs on a Farm""[40]",Miroshka TV,3.69,"February 27, 2018"
9,10,"""Bath Song""[41]",Cocomelon – Nursery Rhymes,3.61,"May 2, 2018"
10,11,"""Phonics Song with Two Words""[42]",ChuChu TV,3.50,"March 6, 2014"
11,12,Sorry,Justin Bieber,3.40,"October 22, 2015"
12,13,Sugar,Maroon 5,3.39,"January 14, 2015"
13,14,Roar,Katy Perry,3.27,"September 5, 2013"
14,15,Counting Stars,OneRepublic,3.19,"May 31, 2013"
15,16,Thinking Out Loud,Ed Sheeran,3.18,"October 7, 2014"
16,17,Dame Tu Cosita,El Chombo featuring Cutty Ranks,3.10,"April 5, 2018"
17,18,Shake It Off,Taylor Swift,3.02,"August 18, 2014"
18,19,Faded,Alan Walker,2.98,"December 3, 2015"
19,20,Lean On,Major Lazer and DJ Snake featuring MØ,2.97,"March 22, 2015"
20,21,Bailando,Enrique Iglesias featuring Descemer Bueno and ...,2.97,"April 11, 2014"
21,22,Dark Horse,Katy Perry featuring Juicy J,2.96,"February 20, 2014"
22,23,Girls Like You,Maroon 5 featuring Cardi B,2.95,"May 31, 2018"
23,24,Let Her Go,Passenger,2.90,"July 25, 2012"
24,25,Mi Gente,J Balvin and Willy William,2.86,"June 29, 2017"
25,26,Hello,Adele,2.78,"October 22, 2015"
26,27,Waka Waka (This Time for Africa),Shakira featuring Freshlyground,2.73,"June 4, 2010"
27,28,Perfect,Ed Sheeran,2.73,"November 9, 2017"
28,29,Blank Space,Taylor Swift,2.71,"November 10, 2014"
29,30,Chantaje,Shakira featuring Maluma,2.62,"November 18, 2016"

# 2) BCCI: India match fixtures

In [6]:
def bcci():
    driver = webdriver.Firefox(executable_path = GeckoDriverManager().install())
    csv_file = open('matches.csv', 'w')
    writer = csv.writer(csv_file)
    writer.writerow(['Date', 'Time', 'Format', 'Series', 'Location'])
    driver.get('https://www.bcci.tv/')
    time.sleep(5)
    url = driver.find_element_by_css_selector('.navigation__list > li:nth-child(1) > div:nth-child(2) > div:nth-child(1) > ul:nth-child(2) > li:nth-child(1) > a:nth-child(1)').get_attribute('href')
    driver.get(url)
    time.sleep(5)
    for i in range(1,25):
        try:
            date = driver.find_element_by_css_selector('a.js-match:nth-child({}) > div:nth-child(1)'.format(i)).text.split('\n')
            tme = ' '.join([str(elem) for elem in date[3:]])
            date = ' '.join([str(elem) for elem in date[1:3]])

            match_type = driver.find_element_by_css_selector('a.js-match:nth-child({}) > div:nth-child(2) > div:nth-child(2) > p:nth-child(2) > strong:nth-child(1)'.format(i)).text

            series = driver.find_element_by_css_selector('a.js-match:nth-child({}) > div:nth-child(2) > div:nth-child(1) > span:nth-child(2)'.format(i)).text

            location = driver.find_element_by_css_selector('a.js-match:nth-child({}) > div:nth-child(2) > div:nth-child(2) > p:nth-child(2) > span:nth-child(2)'.format(i)).text

            writer.writerow([date,tme,match_type,series,location])
        except:
            pass
        
    csv_file.close()

In [7]:
bcci()
pd.read_csv('matches.csv')

[WDM] - Driver [/home/aditya/.wdm/drivers/geckodriver/linux64/v0.29.0/geckodriver] found in cache

,Date,Time,Format,Series,Location
0,13 FEBRUARY,09:30 IST,2nd Test,INDIA V ENGLAND 2021,"M. A. Chidambaram Stadium, Chennai"
1,24 FEBRUARY,14:30 IST,3rd Test,INDIA V ENGLAND 2021,"Sardar Patel Stadium, Ahmedabad"
2,04 MARCH,09:30 IST,4th Test,INDIA V ENGLAND 2021,"Sardar Patel Stadium, Ahmedabad"
3,12 MARCH,19:00 IST,1st T20I,INDIA V ENGLAND 2021,"Sardar Patel Stadium, Ahmedabad"
4,14 MARCH,19:00 IST,2nd T20I,INDIA V ENGLAND 2021,"Sardar Patel Stadium, Ahmedabad"
5,16 MARCH,19:00 IST,3rd T20I,INDIA V ENGLAND 2021,"Sardar Patel Stadium, Ahmedabad"
6,18 MARCH,19:00 IST,4th T20I,INDIA V ENGLAND 2021,"Sardar Patel Stadium, Ahmedabad"
7,20 MARCH,19:00 IST,5th T20I,INDIA V ENGLAND 2021,"Sardar Patel Stadium, Ahmedabad"
8,23 MARCH,13:30 IST,1st ODI,INDIA V ENGLAND 2021,"Maharashtra Cricket Association Stadium, Pune"
9,26 MARCH,13:30 IST,2nd ODI,INDIA V ENGLAND 2021,"Maharashtra Cricket Association Stadium, Pune"
10,28 MARCH,13:30 IST,3rd ODI,INDIA V ENGLAND 2021,"Maharashtra Cricket Association Stadium, Pune"
11,04 AUGUST,15:30 IST,1st Test,ENGLAND V INDIA 2021,"Trent Bridge, Nottingham"
12,12 AUGUST,15:30 IST,2nd Test,ENGLAND V INDIA 2021,"Lord's, London"
13,25 AUGUST,15:30 IST,3rd Test,ENGLAND V INDIA 2021,"Headingley, Leeds"
14,02 SEPTEMBER,15:30 IST,4th Test,ENGLAND V INDIA 2021,"The Oval, London"
15,10 SEPTEMBER,15:30 IST,5th Test,ENGLAND V INDIA 2021,"Old Trafford, Manchester"

# 3) Guru99: Selenium exception details

In [8]:
def guru99():
    csv_file = open('exception.csv', 'w')
    writer = csv.writer(csv_file)
    writer.writerow(['Exception', 'Description'])
    driver = webdriver.Firefox(executable_path = GeckoDriverManager().install())
    driver.get('https://www.guru99.com')
    driver.find_element_by_css_selector('.cloumnsize1 > ul:nth-child(2) > li:nth-child(3) > a:nth-child(1)').click()
    driver.find_element_by_css_selector('table.table:nth-child(25) > tbody:nth-child(1) > tr:nth-child(34) > td:nth-child(1) > a:nth-child(2)').click()
    for i in range(2,43):
        exception = driver.find_element_by_css_selector('.table > tbody:nth-child(1) > tr:nth-child({}) > td:nth-child(1)'.format(i)).text
        desc = driver.find_element_by_css_selector('.table > tbody:nth-child(1) > tr:nth-child({}) > td:nth-child(2)'.format(i)).text
        writer.writerow([exception, desc])
    csv_file.close()

In [9]:
guru99()
pd.read_csv('exception.csv')

[WDM] - Driver [/home/aditya/.wdm/drivers/geckodriver/linux64/v0.29.0/geckodriver] found in cache

,Exception,Description
0,ElementNotVisibleException,This type of Selenium exception occurs when an...
1,ElementNotSelectableException,This Selenium exception occurs when an element...
2,NoSuchElementException,This Exception occurs if an element could not ...
3,NoSuchFrameException,This Exception occurs if the frame target to b...
4,NoAlertPresentException,This Exception occurs when you switch to no pr...
5,NoSuchWindowException,This Exception occurs if the window target to ...
6,StaleElementReferenceException,This Selenium exception occurs happens when th...
7,SessionNotFoundException,The WebDriver is acting after you quit the bro...
8,TimeoutException,Thrown when there is not enough time for a com...
9,WebDriverException,This Exception takes place when the WebDriver ...
10,ConnectionClosedException,This type of Exception takes place when there ...
11,ElementClickInterceptedException,The command may not be completed as the elemen...
12,ElementNotInteractableException,This Selenium exception is thrown when any ele...
13,ErrorInResponseException,This happens while interacting with the Firefo...
14,ErrorHandler.UnknownServerException,Exception is used as a placeholder in case if ...
15,ImeActivationFailedException,This expectation will occur when IME engine ac...
16,ImeNotAvailableException,It takes place when IME support is unavailable.
17,InsecureCertificateException,Navigation made the user agent to hit a certif...
18,InvalidArgumentException,It occurs when an argument does not belong to ...
19,InvalidCookieDomainException,This happens when you try to add a cookie unde...
20,InvalidCoordinatesException,This type of Exception matches an interacting ...
21,InvalidElementStateExceptio,It occurs when command can't be finished when ...
22,InvalidSessionIdException,This Exception took place when the given sessi...
23,InvalidSwitchToTargetException,This occurs when the frame or window target to...
24,JavascriptException,This issue occurs while executing JavaScript g...
25,JsonException,It occurs when you afford to get the session w...
26,NoSuchAttributeException,This kind of Exception occurs when the attribu...
27,MoveTargetOutOfBoundsException,It takes place if the target provided to the A...
28,NoSuchContextException,ContextAware does mobile device testing.
29,NoSuchCookieException,This Exception occurs when no cookie matching ...
30,NotFoundException,This Exception is a subclass of WebDriverExcep...
31,RemoteDriverServerException,This Selenium exception is thrown when the ser...
32,ScreenshotException,It is not possible to capture a screen.
33,SessionNotCreatedException,It happens when a new session could not be suc...
34,UnableToSetCookieException,This occurs if a driver is unable to set a coo...
35,UnexpectedTagNameException,Happens if a support class did not get a web e...
36,UnhandledAlertException,This expectation occurs when there is an alert...
37,UnexpectedAlertPresentException,It occurs when there is the appearance of an u...
38,UnknownMethodException,This Exception happens when the requested comm...
39,UnreachableBrowserException,This Exception occurs only when the browser is...
40,UnsupportedCommandException,This occurs when remote WebDriver does n't sen...

# 4) Statistictime: Indian State GDP

In [10]:
def stategdp():
    csv_file = open('gdp.csv', 'w')
    writer = csv.writer(csv_file)
    writer.writerow(['Rank','State', 'GDP_2020', 'GDP_2019', 'GDP_billions', 'GDP_share'])
    driver = webdriver.Firefox(executable_path = GeckoDriverManager().install())
    driver.get('http://statisticstimes.com/')
    time.sleep(5)
    url = driver.find_element_by_css_selector('div.dropdown:nth-child(2) > div:nth-child(2) > a:nth-child(3)').get_attribute('href')
    driver.get(url)
    time.sleep(5)
    driver.find_element_by_css_selector('body > div:nth-child(2) > div:nth-child(6) > div:nth-child(2) > ul:nth-child(2) > li:nth-child(1) > a:nth-child(1)').click()
    time.sleep(5)
    rank = 1
    for i in range(1,34):
        try:
            state = driver.find_element_by_css_selector('#table_id > tbody:nth-child(3) > tr:nth-child({}) > td:nth-child(2)'.format(i)).text
            gdp_20= driver.find_element_by_css_selector('#table_id > tbody:nth-child(3) > tr:nth-child({}) > td:nth-child(3)'.format(i)).text
            gdp_19=driver.find_element_by_css_selector('#table_id > tbody:nth-child(3) > tr:nth-child({}) > td:nth-child(4)'.format(i)).text
            gdp_billions=driver.find_element_by_css_selector('#table_id > tbody:nth-child(3) > tr:nth-child({}) > td:nth-child(6)'.format(i)).text
            share = driver.find_element_by_css_selector('#table_id > tbody:nth-child(3) > tr:nth-child({}) > td:nth-child(5)'.format(i)).text
            writer.writerow([rank, state, gdp_20, gdp_19, gdp_billions, share])
        except:                                    
            continue
    csv_file.close()

In [11]:
stategdp()
pd.read_csv('gdp.csv')

[WDM] - Driver [/home/aditya/.wdm/drivers/geckodriver/linux64/v0.29.0/geckodriver] found in cache

,Rank,State,GDP_2020,GDP_2019,GDP_billions,GDP_share
0,1,Maharashtra,-,"2,632,792",398.145,13.88%
1,1,Uttar Pradesh,"1,794,508","1,668,229",252.278,8.79%
2,1,Tamil Nadu,"1,845,853","1,630,208",246.529,8.59%
3,1,Karnataka,"1,699,115","1,544,399",233.552,8.14%
4,1,Gujarat,-,"1,502,899",227.276,7.92%
5,1,West Bengal,"1,253,832","1,089,898",164.820,5.75%
6,1,Rajasthan,"1,020,989","942,586",142.543,4.97%
7,1,Andhra Pradesh,"972,782","862,957",130.501,4.55%
8,1,Telangana,"969,604","861,031",130.210,4.54%
9,1,Madhya Pradesh,"906,672","809,592",122.431,4.27%
10,1,Kerala,-,"781,653",118.206,4.12%
11,1,Delhi,"856,112","774,870",117.180,4.08%
12,1,Haryana,"831,610","734,163",111.024,3.87%
13,1,Bihar,"611,804","530,363",80.204,2.80%
14,1,Punjab,"574,760","526,376",79.601,2.77%
15,1,Odisha,"531,374","492,229",74.437,2.59%
16,1,Assam,-,"315,881",47.769,1.67%
17,1,Chhattisgarh,"329,180","304,063",45.982,1.60%
18,1,Jharkhand,"328,598","297,204",44.945,1.57%
19,1,Uttarakhand,-,"245,895",37.186,1.30%
20,1,Jammu & Kashmir,-,"155,956",23.584,0.82%
21,1,Himachal Pradesh,"165,472","153,845",23.265,0.81%
22,1,Goa,-,"73,170",11.065,0.39%
23,1,Tripura,"55,358","49,845",7.538,0.26%
24,1,Chandigarh,-,"42,114",6.369,0.22%
25,1,Puducherry,"40,802","36,656",5.543,0.19%
26,1,Meghalaya,"36,572","33,481",5.063,0.18%
27,1,Sikkim,"32,496","28,723",4.344,0.15%
28,1,Manipur,-,"27,869",4.214,0.15%
29,1,Nagaland,-,"27,283",4.126,0.14%
30,1,Arunachal Pradesh,-,"24,603",3.721,0.13%
31,1,Mizoram,-,"19,520",2.952,0.10%
32,1,Andaman & Nicobar Islands,-,-,-,-

# 5) Github: Repositories

In [12]:
def github():
    csv_file = open('github.csv', 'w')
    writer = csv.writer(csv_file)
    writer.writerow(['Title', 'Language', 'No. of Contributors', 'Description'])
    driver = webdriver.Firefox(executable_path = GeckoDriverManager().install())
    driver.get('https://github.com/')
    time.sleep(5)
    url = driver.find_element_by_css_selector('ul.mb-3:nth-child(3) > li:nth-child(3) > a:nth-child(1)').get_attribute('href')
    driver.get(url)
    time.sleep(5)
    for i in range(1,26):
        try:
            title = driver.find_element_by_css_selector('article.Box-row:nth-child({}) > h1:nth-child(2) > a:nth-child(1)'.format(i)).text
        except:
            title = '-'
        try:
            desc = driver.find_element_by_css_selector('article.Box-row:nth-child({}) > p:nth-child(3)'.format(i)).text
        except:
            desc = '-'
        try:    
            lang = driver.find_element_by_css_selector('article.Box-row:nth-child({}) > div:nth-child(4) > span:nth-child(1) > span:nth-child(2)'.format(i)).text
        except:
            lang = '-'
        try:
            contri = driver.find_element_by_css_selector('article.Box-row:nth-child({}) > div:nth-child(4) > span:nth-child(4)'.format(i))
            num = len(contri.find_elements_by_class_name('d-inline-block'))
        except:
            num = '-'
        writer.writerow([title, lang, num, desc])
    csv_file.close()

In [13]:
github()
pd.read_csv('github.csv')

[WDM] - Driver [/home/aditya/.wdm/drivers/geckodriver/linux64/v0.29.0/geckodriver] found in cache

,Title,Language,No. of Contributors,Description
0,conwnet / github1s,TypeScript,3,One second to read GitHub code with VS Code.
1,Azure / azure-quickstart-templates,PowerShell,5,Azure Quickstart Templates
2,iam-abbas / Reddit-Stock-Trends,Python,5,Fetch currently trending stocks on Reddit
3,Azure / azure-rest-api-specs,TypeScript,5,The source for REST API specifications for Mic...
4,iptv-org / iptv,JavaScript,5,Collection of 5000+ publicly available IPTV ch...
5,JonnyBurger / remotion,TypeScript,5,Create videos programmatically in React
6,hashicorp / vault,Go,5,"A tool for secrets management, encryption as a..."
7,aws / amazon-sagemaker-examples,Jupyter Notebook,5,Example notebooks that show how to apply machi...
8,felixge / go-profiler-notes,Jupyter Notebook,2,My notes on the various go profiling methods t...
9,JonnyBurger / remotion-trailer,TypeScript,1,A video written in React
10,mozilla-mobile / firefox-ios,Swift,5,Firefox for iOS
11,Azure / azure-powershell,C#,5,Microsoft Azure PowerShell
12,sveltejs / svelte,TypeScript,5,Cybernetically enhanced web apps
13,excalidraw / excalidraw,TypeScript,5,Virtual whiteboard for sketching hand-drawn li...
14,engindemirog / KampFinalProject,C#,2,Yazılım Geliştirici Yetiştirme Kampı Büyük Proje
15,streamich / react-use,TypeScript,5,React Hooks —
16,hashicorp / terraform-provider-aws,Go,5,Terraform AWS provider
17,jomjol / AI-on-the-edge-device,-,-,-
18,goldbergyoni / nodebestpractices,JavaScript,5,The Node.js best practices list (February 2021)
19,Seagate / cortx,Jupyter Notebook,5,CORTX Community Object Storage is 100% open so...
20,reed-hong / awesome-libra,-,0,A Curated List of Awesome Facebook Libra Resou...
21,inancgumus / learngo,Go,5,"1000+ Hand-Crafted Go Examples, Exercises, and..."
22,swisskyrepo / PayloadsAllTheThings,Python,5,A list of useful payloads and bypass for Web A...
23,EvotecIT / GPOZaurr,PowerShell,1,Group Policy Eater is a PowerShell module that...
24,flybywiresim / a32nx,JavaScript,5,The A32NX Project is a community driven open s...

# 6) BillBoard: top100 songs

In [14]:
def billboard():
    csv_file = open('top100.csv', 'w')
    writer = csv.writer(csv_file)
    writer.writerow(['Rank', 'Song', 'Artist', 'Last Week Rank', 'Peak Rank', 'Weeks on Chart'])
    driver = webdriver.Firefox(executable_path = GeckoDriverManager().install())
    driver.get('https://www.billboard.com/')
    time.sleep(5)
    driver.find_element_by_css_selector('li.header__subnav__item:nth-child(3) > a:nth-child(1)').click()
    time.sleep(10)
    rank = 1
    for i in range(1, 110):
        try:
            try:
                song = driver.find_element_by_css_selector('li.chart-list__element:nth-child({}) > button:nth-child(1) > span:nth-child(2) > span:nth-child(1)'.format(i)).text
            except:
                continue
            try:
                artist = driver.find_element_by_css_selector('li.chart-list__element:nth-child({}) > button:nth-child(1) > span:nth-child(2) > span:nth-child(2)'.format(i)).text
            except:
                artist = '-'
            try:
                last_week = driver.find_element_by_css_selector('li.chart-list__element:nth-child({}) > button:nth-child(1) > div:nth-child(3) > div:nth-child(2)'.format(i)).text
            except:
                last_week = '-'
            try:
                peak = driver.find_element_by_css_selector('li.chart-list__element:nth-child({}) > button:nth-child(1) > div:nth-child(3) > div:nth-child(3)'.format(i)).text
            except:
                peak = '-'
            try:
                weeks = driver.find_element_by_css_selector('li.chart-list__element:nth-child({}) > button:nth-child(1) > div:nth-child(3) > div:nth-child(4)'.format(i)).text
            except:
                weeks = '-'
            writer.writerow([rank, song, artist, last_week, peak, weeks])
            rank = rank+1
        except:
            pass
    csv_file.close()

In [15]:
billboard()
pd.read_csv('top100.csv')

[WDM] - Driver [/home/aditya/.wdm/drivers/geckodriver/linux64/v0.29.0/geckodriver] found in cache

,Rank,Song,Artist,Last Week Rank,Peak Rank,Weeks on Chart
0,1,Drivers License,Olivia Rodrigo,1,1,4
1,2,Mood,24kGoldn Featuring iann dior,1,26,-
2,3,Blinding Lights,The Weeknd,1,61,-
3,4,34+35,Ariana Grande,2,14,-
4,5,Levitating,Dua Lipa Featuring DaBaby,5,18,-
...,...,...,...,...,...,...
95,96,Fake Woke,Tom MacDonald,-,96,1
96,97,Prisoner,Miley Cyrus Featuring Dua Lipa,54,11,-
97,98,Dangerous,Morgan Wallen,-,62,3
98,99,Almost Maybes,Jordan Davis,-,95,2
99,100,Mr. Right Now,21 Savage & Metro Boomin Featuring Drake,10,18,-

# 7) Naukri: Data science Recruiters

In [16]:
def naukri():
    csv_file = open('datascience_recruiter.csv', 'w')
    writer = csv.writer(csv_file)
    writer.writerow(['Name', 'Designation', 'Company', 'Location', 'Skills/Roles'])
    driver = webdriver.Firefox(executable_path = GeckoDriverManager().install())
    driver.get('https://www.naukri.com/')
    time.sleep(10)
    url = driver.find_element_by_css_selector('.midSec > li:nth-child(2) > a:nth-child(1)').get_attribute('href')
    driver.get(url)
    time.sleep(10)
    driver.find_element_by_css_selector('.lftBrd > div:nth-child(2) > input:nth-child(1)').send_keys('Data Science')
    time.sleep(5)
    driver.find_element_by_css_selector('#qsbFormBtn').click()
    time.sleep(10)
    j,k = 1,2
    for i in range(1,26):
        try:
            name1 = driver.find_element_by_css_selector('div.outerRecSec:nth-child({}) > div:nth-child({}) > div:nth-child(1) > div:nth-child(1) > p:nth-child(2) > a:nth-child(1) > span:nth-child(1)'.format(i,j)).text
        except:
            name1 = '-'
        try:
            name2 = driver.find_element_by_css_selector('div.outerRecSec:nth-child({}) > div:nth-child({}) > div:nth-child(1) > div:nth-child(1) > p:nth-child(2) > a:nth-child(1) > span:nth-child(1)'.format(i,k)).text
        except:
            name2 = '-'
        try:
            designation1 = driver.find_element_by_css_selector('div.outerRecSec:nth-child({}) > div:nth-child({}) > div:nth-child(1) > div:nth-child(1) > p:nth-child(2) > span:nth-child(2)'.format(i,j)).text
        except:
            designation1 = '-'
        try:   
            designation2 = driver.find_element_by_css_selector('div.outerRecSec:nth-child({}) > div:nth-child({}) > div:nth-child(1) > div:nth-child(1) > p:nth-child(2) > span:nth-child(2)'.format(i,k)).text
        except:
            designation2 = '-'
        try:
            company1 = driver.find_element_by_css_selector('div.outerRecSec:nth-child({}) > div:nth-child({}) > div:nth-child(1) > div:nth-child(1) > p:nth-child(2) > a:nth-child(3)'.format(i,j)).text
        except:
            company1 = '-'
        try:
            company2 = driver.find_element_by_css_selector('div.outerRecSec:nth-child({}) > div:nth-child({}) > div:nth-child(1) > div:nth-child(1) > p:nth-child(2) > a:nth-child(3)'.format(i,k)).text
        except:
            company2 = '-'
        try:
            skills1 = driver.find_element_by_css_selector('div.outerRecSec:nth-child({}) > div:nth-child({}) > div:nth-child(1) > div:nth-child(3)'.format(i,j)).text
        except:
            skills1 = '-'
        try:
            skills2 = driver.find_element_by_css_selector('div.outerRecSec:nth-child({}) > div:nth-child({}) > div:nth-child(1) > div:nth-child(3)'.format(i,k)).text
        except:
            skills2 = '-'
        try:
            location1 = driver.find_element_by_css_selector('div.outerRecSec:nth-child({}) > div:nth-child({}) > div:nth-child(1) > div:nth-child(1) > p:nth-child(2) > span:nth-child(4) > small:nth-child(2)'.format(i,j)).text
        except:
            location1 = '-'
        try:
            location2 = driver.find_element_by_css_selector('div.outerRecSec:nth-child({}) > div:nth-child({}) > div:nth-child(1) > div:nth-child(1) > p:nth-child(2) > span:nth-child(4) > small:nth-child(2)'.format(i,k)).text
        except:
            location2 = '-'
        writer.writerow([name1, designation1, company1, location1, skills1])
        writer.writerow([name2, designation2, company2, location2, skills2])
    csv_file.close()

In [17]:
naukri()
pd.read_csv('datascience_recruiter.csv')

[WDM] - Driver [/home/aditya/.wdm/drivers/geckodriver/linux64/v0.29.0/geckodriver] found in cache

,Name,Designation,Company,Location,Skills/Roles
0,Aakash Harit,HR Manager,Data Science Network,Delhi,"Classic ASP Developer, Internet Marketing Prof..."
1,shravan Kumar Gaddam,Company Recruiter,Shore Infotech India Pvt. Ltd,Hyderabad / Secunderabad,".Net, Java, Data Science, Linux Administration..."
2,Talent Acquisition Executive,Recruitment Professional,XenonStack,Chandigarh,"Web Designing, html5, Angular.js, seo, hadoop,..."
3,Anik Agrawal,Company Recruiter,Enerlytics Software Solutions Pvt Ltd,Ahmedabad,"Mean Stack, javascript, angularjs, mongodb, We..."
4,MARSIAN Technologies LLP,Company HR,MARSIAN Technologies LLP,Pune,"Data Science, Artificial Intelligence, Machine..."
5,subhas patel,Founder CEO,LibraryXProject,UK - (london),"Hadoop, Spark, Digital Strategy, Data Architec..."
6,Jitendra Singh,Manager- Talent Acquisition,Compunnel Technology India Pvt. Ltd,Delhi,"Python, Data Science, .Net, Java, Big Data, Da..."
7,Abhishek - Only Analytics Hiring - India and,Recruitment Lead Consultant,Apidel Technologies Division of Transpower,Vadodara / Baroda,"Analytics, Business Intelligence, Business Ana..."
8,Institute for Financial Management and Resear,Programme Manager,IFMR,Chennai,Data Science
9,Balu Ramesh,HR Administrator,Techvantage Systems Pvt Ltd,Trivandrum,"Machine Learning, algorithms, Go Getter, Compu..."
10,Asif Lucknowi,Director,Weupskill- Live Wire India,Indore,"Technical Training, Software Development, Pres..."
11,InstaFinancials,Human Resource,CBL Data Science Private Limited,Bengaluru / Bangalore,"Software Development, It Sales, Account Manage..."
12,Kalpana Dumpala,Executive Hiring,Innominds Software,Hyderabad / Secunderabad,"Qa, Ui/ux, Java Developer, Java Architect, C++..."
13,Mubarak,Company HR,MoneyTap,Bengaluru / Bangalore,"Business Intelligence, Data Warehousing, Data ..."
14,Kushal Rastogi,Company HR,QuantMagnum Technologies Pvt. Ltd.,Mumbai,"Office Administration, Hr Administration, tele..."
15,Manisha Yadav,HR Executive,Easi Tax,Navi Mumbai,"Telecalling, Client Interaction, Marketing, Re..."
16,Kapil Devang,HR Manager,BISP Solutions,Bhopal,"Big Data, Hadoop, Data Analytics, Data Science"
17,Riya Rajesh,Manager Talent Acquisition,Novelworx Digital Solutions,Cochin,Data Science
18,Mahesh Babu Channa,HR Team Lead,SocialPrachar.com,Hyderabad / Secunderabad,"Social Media, digital media maketing, seo, smm..."
19,Rashmi Bhattacharjee,HR Head,AXESTRACK SOFTWARE SOLUTIONS PRIVATE...,Delhi,"Corporate Sales, Software Development, Softwar..."
20,Faizan Kareem,HR MANAGER,FirstTech Consaltants Pvt.Ltd,Hyderabad / Secunderabad,"Data Analytics, Data Science, Machine Learning..."
21,Rithika dadwal,HR Recruiter,Affine Analytics,Pune,"Data Science, Machine Learning, Python, R, Dee..."
22,Azahar Shaikh,Company Recruiter,NEAL ANALYTICS SERVICES PVT LTD,Pune,"Data Science, Artificial Intelligence, Machine..."
23,Sandhya Khandagale,HR Recruiter,Compumatrice Multimedia Pvt Ltd,Pune,"Big Data, Data Science, Artificial Intelligenc..."
24,Shaun Rao,Manager Human Resources,Exela Technologies,Pune,"Java, Net, Angularjs, Hr, Infrastructure, Mana..."
25,Manas,Lead Talent acquisition,Autumn Leaf Consulting Services Private...,Bengaluru / Bangalore,"Software Architecture, Vp Engineering, Product..."
26,kumar,Proprietor,trainin,Bengaluru / Bangalore,"Data Science, Hadoop, Rpas, Devops, Python, Aw..."
27,Sunil Vedula,CEO,Nanoprecise Sci Corp,-,"Signal Processing, Machine Learning, Neural Ne..."
28,Rajat Kumar,Founder CEO,R.S Consultancy &amp; Services,Delhi,"Web Technologies, Project Management, Software..."
29,Jayanth N,Project Manager,"Dollarbird Information Services Pvt, Ltd",Mysoru / Mysore,"Data Analytics, Managed Services, Team Leading..."
30,Prateek Kumar,Head,Trisect,Noida,"Java, Python, Angularjs, Software Testing, Mac..."
31,Amit Sharma,Consultant,ASCO consulting,New Delhi,"Machine Learning, Artificial Intelligence, Dat..."
32,Kanan,senior technology instructor,NY INST,Chennai,"C, C++, Artificial Intelligence, Python, Php, ..."
33,Shashikant Chaudhary,HR Recruiter/HR Excutive,3D India Staffing Research &amp; Consulting...,Aligarh,"Relationship Management, Retail Sales, Private..."
34,Brad,"Manager, Technical Recruiting",O.C. Tanner,Salt Lake City,"Data Science, Software Engineering"
35,Rutuja Pawar,Technical Recruiter,Demand Matrix,Pune,"Data Science, Big Data Analytics, Digital Mark..."
36,Madhusudhan Sridhar,Erp Implementer,MADHUSUDHAN SRIDHAR,Bengaluru / Bangalore,"Data Science, Recruitment, Salary"
37,Ankit Sinha,Head Analytics,Suntech Global,Mumbai,"B.Tech, Tableau, Statistics, R, Analytics, Tim..."
38,Gaurav Chouhan,Chief Technical Officer,Strategic Consulting Lab,Indore,"Software Development, Business Intelligence, B..."
39,Rashi Kacker,Sr Product Manager,Impel Labs Pvt. Ltd.,Bengaluru / Bangalore,"Data Science, Node.js, Angularjs"
40,Ashwini,Director Global Delivery,MRP Advisers,MYSORE,"Data Science, Media Marketing, Resource Planni..."
41,Balaji Kolli,Co Founder,Saras Solutions India Pvt Ltd,Hyderabad / Secunderabad,"Data Analysis, Learning, Data Science, Compute..."
42,Rajani Nagaraj,HR Manager,WildJasmine,Bengaluru / Bangalore,"Java, Hadoop, R, Machine Learning, Spark, Flum..."
43,ROHIT Kumar,Architect,LNT Private Limited,Mumbai,"Software Development, Core Java, Unit Testing,..."
44,Amir Chowdhury,Managing Partner,Granular.ai,-,"Machine Learning, Data Science, Product Manage..."
45,Shailja Mishra,HR Manager,Certybox Pvt.Ltd.,Noida,"consulting, Education Counseling, Educational ..."
46,Sunny Sharma,Managing Director - HR,Western Service Providers,Mumbai,"Software Professionals, Engineering, Technical..."
47,Sagar Lama,Company HR Manager,AdView,Bengaluru / Bangalore,"Full Stack Developers, Product Manager, Data S..."
48,SREEDHAR,Recruitment Consultant,JOBSMILL BUSINESS SOLUTIONS PRIVATE LIMITED,Hyderabad / Secunderabad,"Data Science, Machine Learning, Big Data Analy..."
49,Dr. S. Prasanna Devi,Professor and Head,SRM Institute of Science and Technology,Chennai,"Computer Science, Machine Learning, Deep Learn..."

# 8) Guardian: Top selling books

In [18]:
def books():
    csv_file = open('top_books.csv', 'w')
    writer  = csv.writer(csv_file)
    writer.writerow(['Rank', 'Title', 'Author', 'Volume', 'Publisher', 'Genre'])
    driver = webdriver.Firefox(executable_path = GeckoDriverManager().install())
    driver.get('https://www.theguardian.com/news/datablog/2012/aug/09/best-selling-books-all-time-fifty-shades-grey-compare')
    time.sleep(10)
    rank = 1
    for i in range(0,100):
        title = driver.find_element_by_css_selector('#table-cell-10943-{}-1'.format(i)).text
        author = driver.find_element_by_css_selector('#table-cell-10943-{}-2'.format(i)).text
        volume = driver.find_element_by_css_selector('#table-cell-10943-{}-3'.format(i)).text
        publisher = driver.find_element_by_css_selector('#table-cell-10943-{}-4'.format(i)).text
        genre = driver.find_element_by_css_selector('#table-cell-10943-{}-5'.format(i)).text
        writer.writerow([rank, title, author, volume, publisher, genre])
    csv_file.close()

In [19]:
books()
pd.read_csv('top_books.csv')

[WDM] - Driver [/home/aditya/.wdm/drivers/geckodriver/linux64/v0.29.0/geckodriver] found in cache

,Rank,Title,Author,Volume,Publisher,Genre
0,1,"Da Vinci Code,The","Brown, Dan","5,094,805",Transworld,"Crime, Thriller & Adventure"
1,1,Harry Potter and the Deathly Hallows,"Rowling, J.K.","4,475,152",Bloomsbury,Children's Fiction
2,1,Harry Potter and the Philosopher's Stone,"Rowling, J.K.","4,200,654",Bloomsbury,Children's Fiction
3,1,Harry Potter and the Order of the Phoenix,"Rowling, J.K.","4,179,479",Bloomsbury,Children's Fiction
4,1,Fifty Shades of Grey,"James, E. L.","3,758,936",Random House,Romance & Sagas
...,...,...,...,...,...,...
95,1,"Ghost,The","Harris, Robert","807,311",Random House,General & Literary Fiction
96,1,Happy Days with the Naked Chef,"Oliver, Jamie","794,201",Penguin,Food & Drink: General
97,1,"Hunger Games,The:Hunger Games Trilogy","Collins, Suzanne","792,187",Scholastic Ltd.,Young Adult Fiction
98,1,"Lost Boy,The:A Foster Child's Search for the L...","Pelzer, Dave","791,507",Orion,Biography: General
99,1,Jamie's Ministry of Food:Anyone Can Learn to C...,"Oliver, Jamie","791,095",Penguin,Food & Drink: General

# 9) IMDB: Top viewed series

In [20]:
def imdb():
    csv_file = open('imdb_series.csv', 'w')
    writer = csv.writer(csv_file)
    writer.writerow(['Title', 'Year(s)', 'Genre', 'Runtime', 'Rating', 'Votes'])
    driver = webdriver.Firefox(executable_path = GeckoDriverManager().install())
    driver.get('https://www.imdb.com/list/ls095964455/')
    time.sleep(5)
    for i in range(1, 101):
        name = driver.find_element_by_css_selector('div.lister-item:nth-child({}) > div:nth-child(2) > h3:nth-child(1) > a:nth-child(2)'.format(i)).text
        year = driver.find_element_by_css_selector('div.lister-item:nth-child({}) > div:nth-child(2) > h3:nth-child(1) > span:nth-child(3)'.format(i)).text
        genre = driver.find_element_by_css_selector('div.lister-item:nth-child({}) > div:nth-child(2) > p:nth-child(2) > span:nth-child(5)'.format(i)).text
        runtime = driver.find_element_by_css_selector('div.lister-item:nth-child({}) > div:nth-child(2) > p:nth-child(2) > span:nth-child(3)'.format(i)).text
        rating = driver.find_element_by_css_selector('div.lister-item:nth-child({}) > div:nth-child(2) > div:nth-child(3) > div:nth-child(1) > span:nth-child(2)'.format(i)).text
        votes = driver.find_element_by_css_selector('div.lister-item:nth-child({}) > div:nth-child(2) > p:nth-child(6) > span:nth-child(2)'.format(i)).text
        writer.writerow([name, year, genre, runtime, rating, votes])
    csv_file.close()

In [21]:
imdb()
pd.read_csv('imdb_series.csv')

[WDM] - Driver [/home/aditya/.wdm/drivers/geckodriver/linux64/v0.29.0/geckodriver] found in cache

,Title,Year(s),Genre,Runtime,Rating,Votes
0,Game of Thrones,(2011–2019),"Action, Adventure, Drama",57 min,9.3,"1,768,608"
1,Stranger Things,(2016– ),"Drama, Fantasy, Horror",51 min,8.7,"821,130"
2,The Walking Dead,(2010– ),"Drama, Horror, Thriller",44 min,8.2,"852,846"
3,13 Reasons Why,(2017–2020),"Drama, Mystery, Thriller",60 min,7.6,"256,029"
4,The 100,(2014–2020),"Drama, Mystery, Sci-Fi",43 min,7.6,"216,241"
...,...,...,...,...,...,...
95,Reign,(2013–2017),"Drama, Fantasy",42 min,7.5,"43,551"
96,A Series of Unfortunate Events,(2017–2019),"Adventure, Comedy, Drama",50 min,7.8,"53,836"
97,Criminal Minds,(2005–2020),"Crime, Drama, Mystery",42 min,8.1,"161,036"
98,Scream: The TV Series,(2015–2019),"Crime, Drama, Horror",45 min,7.2,"34,074"
99,The Haunting of Hill House,(2018),"Drama, Horror, Mystery",572 min,8.6,"182,103"

# 10) UCI: ML repositories

In [22]:
def uci():
    csv_file = open('uci_repo.csv', 'w')
    writer = csv.writer(csv_file)
    writer.writerow(['Name', 'Data Type', 'ML Task', 'Attribute Type', 'No of Instances', 'No of Attributes', 'Year'])
    driver = webdriver.Firefox(executable_path = GeckoDriverManager().install())
    driver.get('https://archive.ics.uci.edu/')
    time.sleep(5)
    driver.find_element_by_css_selector('span.whitetext:nth-child(5)').click()
    time.sleep(5)
    for i in range(2,561):
        name = driver.find_element_by_css_selector('body > table:nth-child(3) > tbody:nth-child(1) > tr:nth-child(1) > td:nth-child(2) > table:nth-child(2) > tbody:nth-child(1) > tr:nth-child({}) > td:nth-child(1) > table:nth-child(1) > tbody:nth-child(1) > tr:nth-child(1) > td:nth-child(2) > p:nth-child(1) > b:nth-child(1) > a:nth-child(1)'.format(i)).text
        datatype= driver.find_element_by_css_selector('body > table:nth-child(3) > tbody:nth-child(1) > tr:nth-child(1) > td:nth-child(2) > table:nth-child(2) > tbody:nth-child(1) > tr:nth-child({}) > td:nth-child(2) > p:nth-child(1)'.format(i)).text
        task = driver.find_element_by_css_selector('body > table:nth-child(3) > tbody:nth-child(1) > tr:nth-child(1) > td:nth-child(2) > table:nth-child(2) > tbody:nth-child(1) > tr:nth-child({}) > td:nth-child(3) > p:nth-child(1)'.format(i)).text
        attribute_type = driver.find_element_by_css_selector('body > table:nth-child(3) > tbody:nth-child(1) > tr:nth-child(1) > td:nth-child(2) > table:nth-child(2) > tbody:nth-child(1) > tr:nth-child({}) > td:nth-child(4) > p:nth-child(1)'.format(i)).text
        instances = driver.find_element_by_css_selector('body > table:nth-child(3) > tbody:nth-child(1) > tr:nth-child(1) > td:nth-child(2) > table:nth-child(2) > tbody:nth-child(1) > tr:nth-child({}) > td:nth-child(5) > p:nth-child(1)'.format(i)).text
        attributes=driver.find_element_by_css_selector('body > table:nth-child(3) > tbody:nth-child(1) > tr:nth-child(1) > td:nth-child(2) > table:nth-child(2) > tbody:nth-child(1) > tr:nth-child({}) > td:nth-child(6) > p:nth-child(1)'.format(i)).text
        year = driver.find_element_by_css_selector('body > table:nth-child(3) > tbody:nth-child(1) > tr:nth-child(1) > td:nth-child(2) > table:nth-child(2) > tbody:nth-child(1) > tr:nth-child({}) > td:nth-child(7) > p:nth-child(1)'.format(i)).text
        writer.writerow([name, datatype, task, attribute_type, instances, attributes, year])
    csv_file.close()

In [23]:
uci()
pd.read_csv('uci_repo.csv')

[WDM] - Driver [/home/aditya/.wdm/drivers/geckodriver/linux64/v0.29.0/geckodriver] found in cache

,Name,Data Type,ML Task,Attribute Type,No of Instances,No of Attributes,Year
0,Abalone,Multivariate,Classification,"Categorical, Integer, Real",4177,8,1995
1,Adult,Multivariate,Classification,"Categorical, Integer",48842,14,1996
2,Annealing,Multivariate,Classification,"Categorical, Integer, Real",798,38,
3,Anonymous Microsoft Web Data,,Recommender-Systems,Categorical,37711,294,1998
4,Arrhythmia,Multivariate,Classification,"Categorical, Integer, Real",452,279,1998
...,...,...,...,...,...,...,...
554,IIWA14-R820-Gazebo-Dataset-10Trajectories,,Regression,Integer,,,2020
555,Guitar Chords finger positions,Text,Classification,,2633,5,2020
556,Russian Corpus of Biographical Texts,Text,Classification,,200,2,2020
557,Codon usage,Multivariate,"Classification, Clustering",,13028,69,2020
558,Intelligent Media Accelerometer and Gyroscope ...,Time-Series,Classification,Real,800,9,2020